from __future__ import annotations
from typing import Optional, Literal, Dict, List
from pydantic import BaseModel, Field


class ExtractionStrategy(BaseModel):
    """
    Field-specific hints used by the windowing algorithm to prioritise the
    most relevant chunks of a long page. Generated by the LLM at Phase B2.

    All fields are optional and best-effort: bad hints fall back to pure
    keyword-density scoring (see _select_text_with_strategy safety net).
    """
    value_regex: Optional[str] = None                  # Python regex the value should match
    value_anchors_he: List[str] = Field(default_factory=list)  # context phrases near the value
    value_anchors_en: List[str] = Field(default_factory=list)


class ColumnPlan(BaseModel):
    id: str
    label_he: str
    label_en: str
    type: Literal["person_name", "url", "date", "free_text", "organization", "number"]
    volatility: Literal["stable", "volatile"] = "stable"  # stable=historical, volatile=can change
    temporal_anchor: Optional[str] = None          # e.g. "1990"
    search_queries_he: List[str] = Field(default_factory=list)   # populated in Phase B2
    search_queries_en: List[str] = Field(default_factory=list)   # populated in Phase B2
    preferred_source_domains: List[str] = Field(default_factory=list)
    min_corroborations: int = 1                    # independent domains required
    depends_on: Optional[str] = None               # id of field whose value must resolve first
    directory_probe_query_he: Optional[str] = None  # entity-agnostic query for directory/list pages
    extraction_strategy: Optional[ExtractionStrategy] = None  # windowing hints, generated in Phase B2


class ResearchPlan(BaseModel):
    entity_type: str
    research_question_original: str
    columns: List[ColumnPlan]


class ExtractionResult(BaseModel):
    field_id: str
    value: Optional[str]                # None means "not found" — never a guess
    quote_original: Optional[str]       # exact copy-paste from source text
    source_url: str
    source_domain: str
    is_grounded: bool                   # passed the substring grounding check
    extractor_confidence: float         # 0.0–1.0 self-reported by LLM
    publication_date: Optional[str] = None  # ISO date of the source page, best-effort


class VerifiedCell(BaseModel):
    field_id: str
    label_he: str
    value: Optional[str]
    confidence: Literal["HIGH", "MEDIUM", "LOW", "NOT_FOUND"]
    corroboration_count: int
    primary_source: Optional[dict] = None   # includes url, domain, quote, date
    all_sources: List[dict] = Field(default_factory=list)
    flags: List[str] = Field(default_factory=list)


class EntityResult(BaseModel):
    entity_name: str
    cells: Dict[str, VerifiedCell]
    row_flags: List[str] = Field(default_factory=list)


# ── Guided Prompting ─────────────────────────────────────────────────────────

class ClarificationQuestion(BaseModel):
    field: str          # which aspect is ambiguous (e.g. "timeframe", "entity_type")
    question_he: str    # question to show user in Hebrew
    question_en: str
    example: str        # concrete example answer to guide the user


class ClarificationRequest(BaseModel):
    """Returned by the compiler when the prompt is not yet executable."""
    is_executable: Literal[False] = False
    reason: str                             # short explanation of why it's not executable
    questions: List[ClarificationQuestion]  # what we need the user to clarify
    prompt_template: str                    # a filled-in template they can copy-edit


class ExecutableResearchPlan(BaseModel):
    """Wrapper that signals the prompt passed the preflight check."""
    is_executable: Literal[True] = True
    plan: ResearchPlan


# ── Phase C: Field-clarity Audit ─────────────────────────────────────────────

class FieldAuditIssue(BaseModel):
    field_id: str
    issue_kind: Literal[
        "unbounded",         # e.g. "career path" — no single bounded answer
        "subjective",        # e.g. "best mayor" — no objective answer
        "missing_anchor",    # historical field with no year/period
        "ambiguous_format",  # e.g. "name" — full? nickname? first only?
        "ambiguous_scope",   # e.g. "previous career" — one job? sector? years?
        "no_canonical_source",  # no obvious authoritative source exists
    ]
    explanation_he: str
    explanation_en: str
    suggested_fix_he: str
    suggested_fix_en: str


class FieldAuditReport(BaseModel):
    all_clear: bool
    issues: List[FieldAuditIssue] = Field(default_factory=list)


# ── Step 8: Mock-data preview ─────────────────────────────────────────────────

class MockRow(BaseModel):
    entity_name: str
    values: Dict[str, str]   # field_id -> mock value (clearly synthetic)


# ── Entity Discovery ──────────────────────────────────────────────────────────
#
# Used when the research question implies an open entity set ("the 10 largest
# cities in Israel") rather than a user-provided list. The compiler audits the
# question first; the extractor then runs a single search + LLM call that
# returns BOTH the entity list and any field values already visible on the
# discovery page ("harvest"). The user must approve the list before any
# downstream cells are filled.


class EntityDiscoveryAuditIssue(BaseModel):
    issue_kind: Literal[
        "unbounded_count",        # "the largest cities" — needs a number
        "ambiguous_ranking",      # largest by what? population? area?
        "missing_anchor",         # rankings drift — needs a year
        "subjective_criterion",   # "best mayors" — no objective source
        "no_canonical_source",    # no obvious authoritative list page
    ]
    explanation_he: str
    explanation_en: str
    suggested_fix_he: str
    suggested_fix_en: str


class EntityDiscoveryPlan(BaseModel):
    """How to find the entities. Generated by the compiler."""
    query_he: str
    query_en: str
    expected_count: Optional[int] = None
    extraction_hint: Optional[str] = None
    audit_issues: List[EntityDiscoveryAuditIssue] = Field(default_factory=list)


class DiscoveredEntity(BaseModel):
    name: str
    rank: Optional[int] = None
    quote: Optional[str] = None        # exact substring from source page


class HarvestedValue(BaseModel):
    """Field value already extracted from the discovery page, by entity."""
    entity_name: str
    field_id: str
    value: Optional[str]
    quote: Optional[str]


class EntityDiscoveryResult(BaseModel):
    entities: List[DiscoveredEntity]
    harvested: List[HarvestedValue] = Field(default_factory=list)
    source_url: str
    source_domain: str
